In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    "Name": ["John", "Mary", "Peter", "Linda", None],
    "Age": [25, 30, np.nan, 28, 22],
    "Department": ["IT", "HR", "Finance", None, "IT"],
    "Salary": [50000, 60000, 55000, 52000, None]
}

df = pd.DataFrame(data)
df

    Name   Age Department   Salary
0   John  25.0         IT  50000.0
1   Mary  30.0         HR  60000.0
2  Peter   NaN    Finance  55000.0
3  Linda  28.0       None  52000.0
4   None  22.0         IT      NaN

In [3]:
# Drop rows with null values
df_dropped = df.dropna()

# Drop column
df_no_salary = df.drop(columns=["Salary"])

df_dropped, df_no_salary

(   Name   Age Department   Salary
 0  John  25.0         IT  50000.0
 1  Mary  30.0         HR  60000.0,
     Name   Age Department
 0   John  25.0         IT
 1   Mary  30.0         HR
 2  Peter   NaN    Finance
 3  Linda  28.0       None
 4   None  22.0         IT)

In [4]:
df_filled = df.fillna({
    "Name": "Unknown",
    "Age": df["Age"].mean(),
    "Department": "Not Assigned",
    "Salary": df["Salary"].mean()
})

df_filled

      Name    Age    Department   Salary
0     John  25.00            IT  50000.0
1     Mary  30.00            HR  60000.0
2    Peter  26.25       Finance  55000.0
3    Linda  28.00  Not Assigned  52000.0
4  Unknown  22.00            IT  54250.0

In [5]:
grouped = df_filled.groupby("Department")

grouped.describe()

               Age                                                    Salary  \
             count   mean      std    min    25%    50%    75%    max  count
Department
Finance        1.0  26.25      NaN  26.25  26.25  26.25  26.25  26.25    1.0
HR             1.0  30.00      NaN  30.00  30.00  30.00  30.00  30.00    1.0
IT             2.0  23.50  2.12132  22.00  22.75  23.50  24.25  25.00    2.0
Not Assigned   1.0  28.00      NaN  28.00  28.00  28.00  28.00  28.00    1.0


                 mean         std      min      25%      50%      75%      max
Department
Finance       55000.0         NaN  55000.0  55000.0  55000.0  55000.0  55000.0
HR            60000.0         NaN  60000.0  60000.0  60000.0  60000.0  60000.0
IT            52125.0  3005.20382  50000.0  51062.5  52125.0  53187.5  54250.0
Not Assigned  52000.0         NaN  52000.0  52000.0  52000.0  52000.0  52000.0

In [6]:
df2 = pd.DataFrame({
    "Name": ["Alice", "Bob"],
    "Age": [26, 32],
    "Department": ["IT", "HR"],
    "Salary": [48000, 62000]
})

concat_df = pd.concat([df_filled, df2])
concat_df

      Name    Age    Department   Salary
0     John  25.00            IT  50000.0
1     Mary  30.00            HR  60000.0
2    Peter  26.25       Finance  55000.0
3    Linda  28.00  Not Assigned  52000.0
4  Unknown  22.00            IT  54250.0
0    Alice  26.00            IT  48000.0
1      Bob  32.00            HR  62000.0

In [7]:
dept_info = pd.DataFrame({
    "Department": ["IT", "HR", "Finance"],
    "Location": ["New York", "London", "Toronto"]
})

merged_df = pd.merge(df_filled, dept_info, on="Department", how="left")
merged_df

      Name    Age    Department   Salary  Location
0     John  25.00            IT  50000.0  New York
1     Mary  30.00            HR  60000.0    London
2    Peter  26.25       Finance  55000.0   Toronto
3    Linda  28.00  Not Assigned  52000.0       NaN
4  Unknown  22.00            IT  54250.0  New York